
/* WARNING: Unknown calling convention yet parameter storage is locked */

int connect(int __fd,sockaddr *__addr,socklen_t __len)

{
  int iVar1;
  
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  iVar1 = FUN_00403700();
  return iVar1;
}

