
/* WARNING: Unknown calling convention yet parameter storage is locked */

ssize_t recv(int __fd,void *__buf,size_t __n,int __flags)

{
  ssize_t sVar1;
  
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  sVar1 = FUN_00403700();
  return sVar1;
}

