
/* WARNING: Unknown calling convention yet parameter storage is locked */

int snprintf(char *__s,size_t __maxlen,char *__format,...)

{
  int iVar1;
  
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  (*(code *)__DT_PLTGOT)();
  iVar1 = FUN_00403700();
  return iVar1;
}

